interface dataItem {
  id: number;
  category: string;
  name: string;
  value: string;
}

const data: dataItem[] = [
  { id: 0, category: "main", name: "Brak czynników szkodliwych", value: "Okulista" },
  { id: 1, category: "main", name: "Hałas", value: "Okulista" },
  { id: 2, category: "main", name: "Ultradźwięki małej częstotliwości", value: "Okulista" },
  { id: 3, category: "main", name: "Drgania na kończyny górne", value: "Okulista" },
  { id: 4, category: "main", name: "Drgania na całe ciało", value: "Okulista" },
  { id: 5, category: "main", name: "Promieniowanie jonizujące", value: "Okulista" },
  { id: 6, category: "main", name: "Promieniowanie i pola elektromagnetyczne", value: "Okulista" },
  { id: 7, category: "main", name: "Promieniowanie nadfioletowe", value: "Okulista" },
  { id: 8, category: "main", name: "Promieniowanie podczerwone", value: "Okulista" },
  { id: 9, category: "main", name: "Promieniowanie laserowe", value: "Okulista" },
  { id: 100, category: "main", name: "Promieniowanie widzialne (światło) ", value: "Okulista" },
  { id: 111, category: "main", name: "Obsługa monitorów ekranowych", value: "Okulista" },
  { id: 122, category: "main", name: "Niedostateczne naświetlenie", value: "Okulista" },
  { id: 133, category: "main", name: "Nadmierne naświetlenie", value: "Okulista" },
  { id: 144, category: "main", name: "Mikroklimat gorący", value: "Okulista" },
  { id: 15, category: "main", name: "Mikroklimat zimny  ", value: "Okulista" },
  { id: 16, category: "main", name: "Zwiększone lub obniżone ciśnienie atmosferyczne", value: "Okulista" },
  { id: 17, category: "main", name: "Pyły i włókna", value: "Pyły i włókna" },
  { id: 18, category: "main", name: "Pyły i włókna", value: "Pyły i włókna" },
  { id: 19, category: "main", name: "Pyły i włókna", value: "Pyły i włókna" },
  { id: 20, category: "main", name: "Czynniki toksyczne … jakie?", value: "Okulista" },
  { id: 21, category: "main", name: "Czynniki toksyczne … jakie?", value: "Okulista" },
  { id: 22, category: "main", name: "Czynniki toksyczne … jakie?", value: "Okulista" },
  { id: 23, category: "main", name: "Czynniki toksyczne … jakie?", value: "Okulista" },
  { id: 24, category: "main", name: "Czynniki toksyczne … jakie?", value: "Okulista" },
  { id: 25, category: "main", name: "Pestycydy … jakie?", value: "Okulista" },
  { id: 26, category: "main", name: "Pestycydy … jakie?", value: "Okulista" },
  { id: 27, category: "main", name: "Pestycydy … jakie?", value: "Okulista" },
  { id: 28, category: "main", name: "Pestycydy … jakie?", value: "Okulista" },
  { id: 29, category: "main", name: "Pestycydy … jakie?", value: "Okulista" },
  { id: 30, category: "main", name: "Pirydyna", value: "Okulista" },
  { id: 31, category: "main", name: "Rtęć - metaliczna i jej związki nieorganiczne", value: "Okulista" },
  { id: 32, category: "main", name: "Rtęć - związki organiczne", value: "Okulista" },
  { id: 33, category: "main", name: "Siarkowodór", value: "Okulista" },
  { id: 34, category: "main", name: "Siarki tlenki", value: "Okulista" },
  { id: 35, category: "main", name: "Terpentyna", value: "Okulista" },
  { id: 36, category: "main", name: "Wanad i jego zwiazki ", value: "Okulista" },
  { id: 37, category: "main", name: "Węgla disiarczek", value: "Okulista" },
  { id: 38, category: "main", name: "Węgla tlenek (II)", value: "Okulista" },
  { id: 39, category: "main", name: "Węgla tlenek (IV)", value: "Okulista" },
  { id: 40, category: "main", name: "Węglowodorów alifatycznych związki - związki aminowe", value: "Okulista" },
  { id: 41, category: "main", name: "Węglowodorów alifatycznych związki - związki nitrowe", value: "Okulista" },
  { id: 42, category: "main", name: "Węglowodorów alifatycznych związki - chlorowcopodobne węglowodorów alifatycznych lub alicyklicznych", value: "Okulista" },
  { id: 43, category: "main", name: "Chlorek metylu", value: "Okulista" },
  { id: 44, category: "main", name: "Bromek metylu", value: "Okulista" },
  { id: 45, category: "main", name: "Chlorek metylenu", value: "Okulista" },
  { id: 46, category: "main", name: "Chloroform", value: "Okulista" },
  { id: 47, category: "main", name: "Dichloroetan", value: "Okulista" },
  { id: 48, category: "main", name: "Czterochlorek węgla", value: "Okulista" },
  { id: 49, category: "main", name: "Dibromek etylenu, trichloroetylen, tetrachloroetylen", value: "Okulista" },
  { id: 50, category: "main", name: "Węglowodorów aromatycznych związki nitrowe", value: "Okulista" },
  { id: 51, category: "main", name: "Węglowodorów aromatycznych związki aminowe", value: "Okulista" },
  { id: 52, category: "main", name: "Węglowodorów aromatycznych związki chlorowcopodobne - pochodne benzenu", value: "Okulista" },
  { id: 53, category: "main", name: "Węglowodorów aromatycznych związki chlorowcopodobne - pochodne bifenyli", value: "Okulista" },
  { id: 54, category: "main", name: "Węglowodorów aromatycznych związki chlorowcopodobne - pochodne naftalenu", value: "Okulista" },
  { id: 55, category: "main", name: "Winylobenzen", value: "Okulista" },
  { id: 56, category: "main", name: "Winylu chlorek", value: "Okulista" },
  { id: 57, category: "main", name: "Żywice epoksydowe", value: "Okulista" },
  { id: 58, category: "main", name: "Mieszaniny rozpuszczalników organicznych", value: "Okulista" },
  { id: 59, category: "main", name: "Cytostatyki", value: "Okulista" },
  { id: 60, category: "main", name: "Czynniki biologiczne - Wirus zapalenia wątroby - typ B", value: "Okulista" },
  { id: 61, category: "main", name: "Czynniki biologiczne - Wirus zapalenia wątroby - typ C", value: "Okulista" },
  { id: 62, category: "main", name: "Czynniki biologiczne - Ludzki wirus niedoboru odporności nabytej (HIV)", value: "Okulista" },
  { id: 63, category: "main", name: "Czynniki biologiczne - Pąłeczki Brucella abortus bovis", value: "Okulista" },
  { id: 64, category: "main", name: "Czynniki biologiczne - promieniowanie termofilne, grzyby pleśniowe i inne", value: "Okulista" },
  { id: 65, category: "main", name: "Czynniki biologiczne - prątek gróźlicy, wirus kleszczowego zapalenia mózgu, Borrelia", value: "Okulista" },
  { id: 66, category: "main", name: "Wirus kleszczowego zapalenia mózgu", value: "Okulista" },
  { id: 67, category: "main", name: "Borrelia burgdorferi", value: "Okulista" },
  { id: 68, category: "main", name: "Niekorzystne czynniki psychospoł. - stały duży dopływ informacji i gotowość do odpowiedzi ", value: "Okulista" },
  { id: 69, category: "main", name: "Niekorzystne czynniki psychospołeczne - stanowiska decyzyjne i odpowiedzialność", value: "Okulista" },
  { id: 70, category: "main", name: "Niekorzystne czynniki psychospołeczne - zagrożenia wynikające z narażenia życia", value: "Okulista" },
  { id: 71, category: "main", name: "Niekorzystne czynniki psychospołeczne - zagrożenia wynikające z monotonii pracy", value: "Okulista" },
  {
    id: 72,
    category: "main",
    name: "Niekorzystne czynniki psychospołeczne - zagrożenia wynikające z organizacji pracy (praca pod presją czasu, nierównomierne obłożenie pracą, inne) ",
    value: "Okulista",
  },
  { id: 73, category: "main", name: "Praca związana z obsługą narzędzi, maszyn, urządzeń i poruszających się poza drogami publicznymi pojazdów (wózki widłowe, koparki, itd.) ", value: "Okulista" },
  { id: 74, category: "main", name: "Prace wzmagące pełnej sprawnosci psychoruchowej", value: "Okulista" },
  { id: 75, category: "main", name: "Praca na wysokości", value: "Okulista" },
  { id: 76, category: "main", name: "Praca zmianowa", value: "Okulista" },
  { id: 77, category: "main", name: "Praca fizyczna z wydatkiem energetycznym na pracę powyżej (…)", value: "Okulista" },
  { id: 78, category: "main", name: "Praca w wymuszonej pozycji", value: "Okulista" },
  { id: 79, category: "main", name: "Praca wymagająca ruchów monotypowych kończyn", value: "Okulista" },
  { id: 80, category: "main", name: "Praca wymagająca stałego i długotrwałego wysiłku głosowego", value: "Okulista" },
  { id: 81, category: "main", name: "Praca na stanowiskach związanych z kierowanie pojazdami, szkoleniem i egzaminowaniem kierowców", value: "Okulista" },
  { id: 82, category: "main", name: "Praca związana z posługiwaniem się bronią palną ", value: "Okulista" },
  { id: 83, category: "main", name: "Inne prace związane z narażaniem na czynnik niebezpieczny", value: "Okulista" },
  { id: 84, category: "main", name: "Praca w narażeniu na inny czynnik szkodliwy lub uciążliwy", value: "Okulista" },
];
export default data;
